#!/bin/sh

# how many jobs to look at ?

num_jobs=""
[ $# -gt 0 ] && num_jobs=$1
if [ "$num_jobs" = "" ]
then
  printf "How many jobs to check? [all] "
  read num_jobs
fi

if env | grep -Fq SLURM || env | grep -Fq TACC
then
  cmd='scontrol show jobid'
  jobs=$(squeue -u $USER | grep $USER | awk '{print $1}')
else
  cmd='qstat -f'
  jobs=$(qstat -u $USER | grep $USER | awk '{print $1}')
fi

# if enter pressed
[ "$num_jobs" = "" ] || [ "$num_jobs" = "all" ] && num_jobs="$(echo "$jobs" | wc -l)"

echo "$jobs" | head -n $num_jobs | xargs -I{} $cmd {}  
