#!/usr/bin/env bash

slurmpaths(){
  squeue -o "%10i %Z %t" -u $USER | awk -F"/" '{if(NR > 1){OFS="/"; print $1,$(NF-2),$(NF-1),$NF} else {print $0}}' | column -t
}

pbspaths(){
  JobIDs="$(qstat -f | grep  "Job Id" | awk '{print $NF}')"
  paths="$(qstat -f | sed -n '/PBS_O_WORKDIR/,/PBS_O/p' | sed 's/,PBS.*//;s/PBS_O_WORKDIR=//')"

  partial_paths=()
  while read line1 line2; do
    partial_paths+=("$(echo "$line1 $line2" | tr -d '\n' | sed 's/\s//g' | awk -F'/' '{OFS="/"; print $(NF-3),$(NF-2),$(NF-1)}')")
  done < <(printf "%s\n" "${paths[@]}" | xargs -n2)

  paste <(printf "%s\n" "${JobIDs[@]}") <(printf "%s\n" "${partial_paths[@]}") | column -t
}

if env | grep -Fq SLURM || env | grep -Fq TACC
then
  slurmpaths
else
  psbpaths
fi
