#!/usr/bin/env bash

slurmpaths(){
  squeue -o "%10i %Z %t" -u $USER | awk -F"/" '{if(NR > 1){OFS="/"; print $1,$(NF-2),$(NF-1),$NF} else {print $0}}' | column -t
}

pbspaths(){
  paste <(qstat | grep $USER | awk '{print $1}') <(qstat -f -F json | jq '.Jobs | .[].Variable_List.PBS_O_WORKDIR' | sed 's/"//g') | column -t
}

if env | grep -Fq SLURM || env | grep -Fq TACC
then
  slurmpaths
else
  pbspaths
fi
