#!/usr/bin/env python3
"""
Takes in the output from the travis program after a 'cut'
operation has been performed, which generates one xyz file
containing all cluster geometries. This script takes those
geometries and separates them into individual files in a 
'cluster' subfolder.
"""

import os
import re
import sys

if len(sys.argv) not in [2, 3]:
    print(f"Syntax: {os.path.basename(__file__)} <cluster.xyz> [new directory name]")
    sys.exit(1)

if not sys.argv[1].endswith('.xyz'):
    print('Must pass in an xyz of structures generated by TRAVIS')
    print(f"Syntax: {os.path.basename(__file__)} <cluster.xyz> [new directory name]")
    sys.exit(1)

if len(sys.argv) == 2:
    newdir = 'clusters'
else:
    newdir = sys.argv[2]

clusters = []
tmp = []
with open(sys.argv[1]) as f:
    for line in f:
        if re.search('^\s*[0-9]+$', line) and len(tmp) != 0:
            clusters.append(tmp)
            tmp = []
        tmp.append(line)
    # last step
    clusters.append(tmp)

if not os.path.isdir(newdir):
    os.mkdir(newdir)

for idx, cluster in enumerate(clusters):
    with open(f"{newdir}/cluster-{idx}.xyz", "w") as new:
        for line in cluster:
            new.write(line)
