#!/usr/bin/env bash

[[ $# -eq 0 ]] && echo "Syntax: travis_xyz_analysis traj.lmp" && exit 1
[[ $USER =~ (tmas0023|tommason) ]] && 
  input="$repos/scripts/chem/travis_xyz_analysis.txt" || 
  input="$HOME/chem_scripts/travis_xyz_analysis.txt"

travis -p "$1" -i "$input"
