#!/bin/sh

[ $# -ne 1 ] || [ "$1" = "-h" ] && echo "Syntax: $(basename $0) xyz_from_ovito" && exit 1

xyz="$1"
cat << EOF > input.dat
$xyz
$(head -2 $xyz | tail -1 | sed 's/Lattice=//;s/Origin=//;s/"//g' | awk '{print $1-$10,$5-$11,$9-$12}')
90.0 90.0 90.0
EOF
