#!/usr/bin/env bash

[[ $# -eq 0 ]] && echo "Syntax: $(basename $0) lammpsfile [output.xyz]" && exit 1

output="${2:-output.xyz}"
$sed -n '/Atoms/,/Bonds/p' $1 | grep -v "Atoms\|Bonds\|^\s*$" > raw_atoms

# make array dynamically
# the indices are made automatically by mapfile, starting at 1
# so that they match the numbers of the lammps data file
# assuming a layout like this:
# 1 12.011 # CA
# 2  1.008 # HA

mapfile -t -O 1 atoms < <($sed -n '/Masses/,/^\w/p' $1 |
  grep "^\s*[0-9]\+\s\+[0-9]\+\.[0-9]\+\s*\#" |
  awk '{print $NF}')

# replace the number in the third column with atomic symbol
for i in "${!atoms[@]}"
do
  num="$i"
  atomtype="${atoms[$i]}"
  $sed -i "s/^\s*\([0-9]\+\s\+[0-9]\+\s\+\)$num/\1 $atomtype/" raw_atoms 
done

awk 'BEGIN{OFS="  "} {print $3,$5,$6,$7}' raw_atoms > tmpxyz
numatoms=$(cat tmpxyz | wc -l | $sed 's/^\s*//')

echo "Coords stored in $output"
printf "$numatoms\n\n" > $output
printf '%s %13s %13s %13s\n' $(cat tmpxyz) >> $output

rm raw_atoms tmpxyz
