#!/usr/bin/env bash

[[ $# -eq 0 ]] &&
  echo "Executes command in python." && 
  echo "The math module is imported so you can use functions such as math.exp." &&
  exit 1

python3 -c "import math; print($@)"
