#!/usr/bin/env bash

[[ $# -eq 0 ]] && 
  echo "Syntax: sumcol [-delim] [col]" &&
  echo "i.e. 'sumcol -, 1' to split on commas and sum the first column" &&
  echo "or 'sumcol 3' to split on whitespace and sum the third column" &&
  exit 1 
if [[ $1 =~ ^- ]]; then 
  delim="${1#-}"
  col="$2"
  file="${3:-/dev/stdin}"
else 
  delim=" " 
  col="$1"
  file="${2:-/dev/stdin}"
fi
awk -v col="$col" -F "$delim" '{sum += $col} END {print sum}' "$file"
